### ISSUE TITLE
Upgrading an existing building

### ISSUE THREAD

**Issue by a-pirard** [JOSM/JOSM-areaselector#21]
Hi,

When mapping with AS, I often come across existing buildings that were badly mapped.
They have just a building=yes tag and they are 2 to 5 m off the exact position etc.
In that case, the fastest option is to erase that building and to build a new AS one.
But that is unfair to the original mapper whose name is removed from history.
And, on the other hand, there might be interesting tags to keep,
and it's best to keep the way's ID in case it's in a relation.

So, I suggest to build an AS building that keeps those data from another.
It's similar to the Conflation plugin but done much much more simply.
What I have tediously done manually shows the basis of the simple operation.
- M: merge two nodes: any of the original building with any of the new one.
- C: combine the two ways into one
- possibly reply yes to change the way direction
- select the new tags in case of merge conflict (or present a fast selection dialog)
- delete the nodes of the original building
The original and AS mapper should appear in the history.

Thanks on behalf of original mappers.

**Comment by r00tat** [comment]
Thanks again for your feedback! 

Areaselector automatically merges nodes, that are near to each other. So if you map a building with AS over the existing building, the corners might be merged. if you press C it will combone the new and the old one.

I think automating this is a little hard, because if the building is 4m off, and the nodes are merged the new one will also be 4 m off.

**Comment by a-pirard** [comment]
On 2015-11-11 12:10, Paul wrote :
>
> Thanks again for your feedback!
>
> Areaselector automatically merges nodes, that are near to each other.
> So if you map a building with AS over the existing building, the
> corners might be merged. if you press C it will combone the new and
> the old one.
>
Ah, I didn't think of that because my mind was focused on merging to
attach buildings.
Moving (only) one node to the (some) correct place prior to using AS can
skip having to merge it afterwards, but the rest has still to be done
manually and it would be welcome that AS were doing it automatically,
except Tag Merge which may require a human decision.

So, I suggest the following documentation update:
>
>
>     merge nodes
>
> Normally, the AreSelector plugin creates a polygon having its own, new
> nodes. If the /*merge nodes*/ setting is selected, and if a node
> belonging to another building exists near enough to any node to be
> created, AreSelector will use that node instead of a new one (this
> amounts to merging the two nodes). So
>
>   * AreaSelector will merge the nodes of the neighbouring wall of two
>     attached buildings
>   * if an unprecisely mapped building already exists, (only) one of
>     its node can be moved to the correct position to be used by
>     AreaSelector; after the new building is created, the two ways can
>     be Combined, the tags can be merged, and the old nodes can be
>     deleted.  That is conflation, keeping the history of the old building.
>
"near enough": should be clarified (I met cases where the walls were not
or partially merged and I don't know what to do except correct it)
" belonging to another building": in case AS is used only for buildings,
else another scheme must be devised; you should beware of attaching
buildings to, for example, landuse.

First, decide if you want AeaSelector to make the conflation
automatically and make your own changes to that text. Return me your
updated version. I can add the manual conflation in detail if you like.
>
> I think automating this is a little hard, because if the building is
> 4m off, and the nodes are merged the new one will also be 4 m off.
>
Not if the user is asked to move that node first, which is the way to
unescapably having to indicate the old building.

I think, but I did not spend time to check that, that the Conflation
plugin is too bulky to learn and use.

Hoping this can help,

Cheers

André.

**Comment by a-pirard** [comment]
Hi Paul,

Following our discussion, I propose the following documentation update.
If you automate steps 2-4 with a button in the AS dialog, it will save
many clicks.
Enabling AS to drag a node will save switching out and in of AS mode.

I have many upgrades to do, as probably many users mapping precisely
with AS.
Do you intend to do that automation and should I wait or go on without?


    Keeping History when replacing a building

Sometimes, a building is very badly tagged and the fastest thing to do
is to erase it and make a new one in one click with AreaSelector.  But
it's unfair to the contributor who mapped it because his name is removed
from the History of that building.  Doing the following keeps the History:

 1. *move one node* of the old building to a corner of the area onto
    which AreaSelector will create a node
 2. *use AreaSelector* to create the new building
 3. *select the 2 ways* of the old and the new buildings and
      * click/type command *C to Combine* the 2 ways
      * confirm *Reverse and Combined* if proposed
      * choose the *tags to **merge* and click Apply
 4. *delete* the nodes of the old building

Hoping this can help,
TIA,
Cheers

André.

**Comment by a-pirard** [comment]
Github seems to have discarded the HTML e-mail I sent for you to get the formated text.
Copy and paste here: nope.    I wanted to upload it and it said
Unfortunately, we don’t support that file type. Try again with a PNG, GIF, JPG, DOCX, PPTX, XLSX, TXT, or PDF. 
??????????????????????????????????????????????????????????????

**Comment by a-pirard** [comment]
What is suggested here is in fact almost already implemented in utilsplugin2.
This overly complicated text has been replaced with a "replacing a building..." new bug making it very simple for the mapper to be fair in two clicks.
